[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "buttonless"
option_as_alt = "Both"

[window.dimensions]
columns = 250
lines = 70

[terminal]
osc52 = "CopyPaste"

[debug]
render_timer = false

# [[keyboard.bindings]]
# key = "Apostrophe"
# mods = "Control"
# action = "Esc"
# chars = "\x1b"  # or your desired escape sequence
